remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [Eclipse Starter for Jakarta EE]
description: [Generates code to help get started with Jakarta EE projects using Maven]

links:
  license: LICENSE
  issues_url: site.github.issues_url